/* tslint:disable */
/* eslint-disable */
/**
 * FarmNote
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: yourmail@fhwn.ac.at
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NoteBase
 */
export interface NoteBase {
    /**
     * 
     * @type {string}
     * @memberof NoteBase
     */
    content: string;
    /**
     * 
     * @type {number}
     * @memberof NoteBase
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof NoteBase
     */
    longitude: number;
    /**
     * 
     * @type {number}
     * @memberof NoteBase
     */
    temperature: number;
}

/**
 * Check if a given object implements the NoteBase interface.
 */
export function instanceOfNoteBase(value: object): value is NoteBase {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    if (!('temperature' in value) || value['temperature'] === undefined) return false;
    return true;
}

export function NoteBaseFromJSON(json: any): NoteBase {
    return NoteBaseFromJSONTyped(json, false);
}

export function NoteBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoteBase {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'temperature': json['temperature'],
    };
}

export function NoteBaseToJSON(value?: NoteBase | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': value['content'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'temperature': value['temperature'],
    };
}

