/* tslint:disable */
/* eslint-disable */
/**
 * FarmNote
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: r206067@fhwn.ac.at
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {mapValues} from '../runtime';

/**
 * Schema for creating a new note
 * @export
 * @interface NoteCreate
 */
export interface NoteCreate {
    /**
     *
     * @type {string}
     * @memberof Note
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof NoteCreate
     */
    content: string;
    /**
     *
     * @type {number}
     * @memberof NoteCreate
     */
    latitude: number;
    /**
     *
     * @type {number}
     * @memberof NoteCreate
     */
    longitude: number;
    /**
     *
     * @type {string}
     * @memberof Note
     */
    weather_condition: string;
}

/**
 * Check if a given object implements the NoteCreate interface.
 */
export function instanceOfNoteCreate(value: object): value is NoteCreate {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    if (!('weather_condition' in value) || value['weather_condition'] === undefined) return false;
    return true;
}

export function NoteCreateFromJSON(json: any): NoteCreate {
    return NoteCreateFromJSONTyped(json, false);
}

export function NoteCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoteCreate {
    if (json == null) {
        return json;
    }
    return {
        'title': json['title'],
        'weather_condition': json['weather_condition'],
        'content': json['content'],
        'latitude': json['latitude'],
        'longitude': json['longitude'],
    };
}

export function NoteCreateToJSON(value?: NoteCreate | null): any {
    if (value == null) {
        return value;
    }
    return {
        'title': value['title'],
        'weather_condition': value['weather_condition'],
        'content': value['content'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

